import { FormEvent, useMemo, useState, type CSSProperties } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Edit3, Flag, Plus, Search, Target, Trash2, TrendingUp, X } from "lucide-react";
import { addObjectiveProgress } from "../api/iniciativas";

type Props={objetivos:any[];items:any[];isSuperAdmin?:boolean;canManageAll?:boolean;onCreate:(event:FormEvent<HTMLFormElement>)=>Promise<void>;onChange:(goal:any,action:"Editar"|"Eliminar")=>Promise<void>};
function metrics(goal:any,items:any[]){const linked=items.filter(item=>item.objetivoId===goal.id),linkedProgress=linked.length?Math.round(linked.reduce((sum,item)=>sum+item.avance,0)/linked.length):0,progress=goal.progresos?.[0]?.porcentaje??linkedProgress,now=new Date(),overdue=linked.filter(item=>item.fechaFin&&new Date(item.fechaFin)<now&&item.avance<100).length,status=progress>=100?"Completado":!linked.length&&!goal.progresos?.length?"Sin iniciativas":overdue?"En riesgo":"En curso",dates=linked.flatMap(item=>[item.fechaInicio,item.fechaFin]).filter(Boolean).map(value=>new Date(value));return{linked,progress,overdue,status,progressSource:goal.progresos?.length?"Actualización del equipo":"Promedio de iniciativas",start:dates.length?new Date(Math.min(...dates.map(date=>date.getTime()))):null,end:dates.length?new Date(Math.max(...dates.map(date=>date.getTime()))):null}}

export default function ObjectivesModule({objetivos,items,isSuperAdmin=false,canManageAll=false,onCreate,onChange}:Props){
 const [query,setQuery]=useState(""),[filter,setFilter]=useState("Todos"),[createOpen,setCreateOpen]=useState(false),[selected,setSelected]=useState<any|null>(null),[progressGoal,setProgressGoal]=useState<any|null>(null),[progressValue,setProgressValue]=useState(0),[progressComment,setProgressComment]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState(""),[revision,setRevision]=useState(0);
 const rows=useMemo(()=>objetivos.map(goal=>({...goal,...metrics(goal,items)})),[objetivos,items,revision]),filtered=rows.filter(goal=>(filter==="Todos"||goal.status===filter)&&`${goal.nombre} ${goal.descripcion??""}`.toLowerCase().includes(query.toLowerCase())),average=rows.length?Math.round(rows.reduce((sum,row)=>sum+row.progress,0)/rows.length):0,completed=rows.filter(row=>row.status==="Completado").length,atRisk=rows.filter(row=>row.status==="En riesgo").length;
 const openProgress=(goal:any)=>{setProgressGoal(goal);setProgressValue(goal.progress);setProgressComment("");setError("")};
 const saveProgress=async(event:FormEvent)=>{event.preventDefault();if(!progressGoal)return;try{setSaving(true);const entry=await addObjectiveProgress(progressGoal.id,{porcentaje:progressValue,comentario:progressComment});const original=objetivos.find(goal=>goal.id===progressGoal.id);if(original)original.progresos=[entry,...(original.progresos??[])];setSelected(null);setProgressGoal(null);setRevision(value=>value+1)}catch(e:any){setError(e?.message??"No se pudo guardar el progreso")}finally{setSaving(false)}};
 return <div className="objectives-center">
  <section className="objectives-hero"><div><span>GESTIÓN ESTRATÉGICA</span><h2>Objetivos y resultados</h2><p>{isSuperAdmin?"Administración global: puedes editar, eliminar y actualizar cualquier objetivo directamente.":canManageAll?"Acceso técnico: puedes mantener y actualizar los objetivos de todas las áreas.":"Conecta las iniciativas con resultados medibles y registra los avances del equipo."}</p></div><button className="primary" onClick={()=>setCreateOpen(true)}><Plus/>Nuevo objetivo</button></section>
  <div className="objective-kpis"><article><Target/><div><span>Objetivos activos</span><b>{rows.length}</b><small>{rows.length-completed} requieren seguimiento</small></div></article><article><TrendingUp/><div><span>Avance consolidado</span><b>{average}%</b><small>Promedio del portafolio</small></div></article><article><CheckCircle2/><div><span>Completados</span><b>{completed}</b><small>Resultados alcanzados</small></div></article><article className={atRisk?"has-risk":""}><AlertTriangle/><div><span>En riesgo</span><b>{atRisk}</b><small>{atRisk?"Requieren atención":"Sin alertas críticas"}</small></div></article></div>
  <div className="objective-toolbar"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar objetivo..."/></label><div>{["Todos","En curso","En riesgo","Completado","Sin iniciativas"].map(value=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{value}</button>)}</div></div>
  <div className="objective-grid">{filtered.map(goal=><article className="objective-strategy-card" key={goal.id} onClick={()=>setSelected(goal)} tabIndex={0}><header><span className={`objective-health health-${goal.status.toLowerCase().replace(" ","-")}`}>{goal.status}</span><b>{goal.linked.length||goal._count?.iniciativas||0} iniciativas</b></header><div className="objective-card-main"><div className="objective-ring" style={{"--objective-progress":`${goal.progress*3.6}deg`} as CSSProperties}><strong>{goal.progress}%</strong></div><div><h3>{goal.nombre}</h3><p>{goal.descripcion||"Sin descripción estratégica."}</p></div></div><div className="objective-progress-line"><i><em style={{width:`${goal.progress}%`}}/></i><span>{goal.progress>=100?"Meta alcanzada":`${100-goal.progress}% pendiente`}</span></div><div className="objective-mini-projects">{goal.linked.slice(0,3).map((item:any)=><span key={item.id}><i style={{background:item.color}}/><b>{item.codigo}</b><small>{item.avance}%</small></span>)}{!goal.linked.length&&<p>Registra el progreso o vincula una iniciativa.</p>}</div><footer><span>{goal.overdue?<><AlertTriangle/>{goal.overdue} con retraso</>:<><CheckCircle2/>Seguimiento al día</>}</span><div><button onClick={event=>{event.stopPropagation();openProgress(goal)}}>Actualizar progreso</button><button onClick={event=>{event.stopPropagation();setSelected(goal)}}>Ver detalle</button></div></footer></article>)}{!filtered.length&&<div className="objective-empty"><Target/><b>No encontramos objetivos</b><span>Prueba otro filtro o registra un nuevo objetivo.</span></div>}</div>
  {createOpen&&<div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setCreateOpen(false)}}><form className="event-modal objective-create-modal" onSubmit={async event=>{await onCreate(event);setCreateOpen(false)}}><button type="button" className="close" onClick={()=>setCreateOpen(false)}><X/></button><Target/><h2>Nuevo objetivo estratégico</h2><p>Define un resultado claro; luego podrás registrar su progreso.</p><label>Nombre<input name="nombre" required minLength={3}/></label><label>Descripción<textarea name="descripcion"/></label><div className="modal-actions"><button type="button" onClick={()=>setCreateOpen(false)}>Cancelar</button><button className="primary"><Plus/>Crear objetivo</button></div></form></div>}
  {selected&&<div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section className="objective-detail-modal"><button className="close" onClick={()=>setSelected(null)}><X/></button><div className="objective-detail-head"><div className="objective-ring large" style={{"--objective-progress":`${selected.progress*3.6}deg`} as CSSProperties}><strong>{selected.progress}%</strong></div><div><span className={`objective-health health-${selected.status.toLowerCase().replace(" ","-")}`}>{selected.status}</span><h2>{selected.nombre}</h2><p>{selected.descripcion||"Sin descripción estratégica."}</p><small>{selected.progressSource}</small></div></div><div className="objective-detail-stats"><div><small>Iniciativas vinculadas</small><b>{selected.linked.length}</b></div><div><small>Con retraso</small><b>{selected.overdue}</b></div><div><small>Periodo estimado</small><b>{selected.start?`${selected.start.toLocaleDateString("es-PE")} — ${selected.end.toLocaleDateString("es-PE")}`:"Sin fechas"}</b></div></div><h3>Iniciativas que impulsan este objetivo</h3><div className="objective-detail-projects">{selected.linked.map((item:any)=><article key={item.id}><span style={{background:item.color}}>{item.icono??item.area.slice(0,2)}</span><div><b>{item.codigo} · {item.titulo}</b><small>{item.area} · {item.estado}</small><i><em style={{width:`${item.avance}%`}}/></i></div><strong>{item.avance}%</strong></article>)}{!selected.linked.length&&<div className="objective-link-empty"><Flag/><span>Aún no existen iniciativas vinculadas.</span></div>}</div><div className="objective-detail-actions"><button className="primary" onClick={()=>openProgress(selected)}><TrendingUp/>Actualizar progreso</button><button onClick={()=>onChange(selected,"Editar")}><Edit3/>{canManageAll?"Editar":"Solicitar edición"}</button><button className="danger" disabled={!selected.canDelete} title={selected.canDelete?"Eliminar objetivo":"Solo el creador o la jefatura del área puede eliminarlo"} onClick={()=>onChange(selected,"Eliminar")}><Trash2/>{canManageAll?"Eliminar":"Solicitar eliminación"}</button></div></section></div>}
  {progressGoal&&<div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setProgressGoal(null)}}><form className="event-modal objective-progress-modal" onSubmit={saveProgress}><button type="button" className="close" onClick={()=>setProgressGoal(null)}><X/></button><TrendingUp/><h2>Actualizar progreso</h2><p>{progressGoal.nombre}</p><div className="objective-progress-value"><span>Avance del objetivo</span><strong>{progressValue}%</strong></div><input className="objective-progress-range" type="range" min="0" max="100" value={progressValue} onChange={event=>setProgressValue(Number(event.target.value))}/><label>Comentario del avance<textarea required minLength={3} value={progressComment} onChange={event=>setProgressComment(event.target.value)} placeholder="Describe qué se logró y cuál es el siguiente paso"/></label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={saving}>{saving?"Guardando...":"Guardar progreso"}</button>{progressGoal.progresos?.length>0&&<section className="objective-progress-history"><h3>Historial</h3>{progressGoal.progresos.slice(0,8).map((entry:any)=><article key={entry.id??entry.createdAt}><Clock3/><div><b>{entry.porcentaje}%</b><p>{entry.comentario}</p><small>{entry.usuario?`${entry.usuario.nombres} ${entry.usuario.apellidos} · `:""}{new Date(entry.createdAt).toLocaleString("es-PE")}</small></div></article>)}</section>}</form></div>}
 </div>
}
