import { FormEvent, useEffect, useState } from "react";
import { AlertTriangle, Download, FileCheck2, FileSignature, FileText, Fingerprint, Plus, ShieldCheck, Upload, UserCheck, X, XCircle } from "lucide-react";
import { createCollaboration, fetchCollaboration, fetchMySignature, rejectDocument, saveMySignature, signDocument } from "../api/iniciativas";
type Row={id:string;datos:any;creador:any;createdAt:string};
export default function SecureSignature({user,team}:{user:any;team:any[]}){
 const [rows,setRows]=useState<Row[]>([]),[uploadOpen,setUploadOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false),[preview,setPreview]=useState<Row|null>(null),[signing,setSigning]=useState<Row|null>(null),[rejecting,setRejecting]=useState<Row|null>(null),[profile,setProfile]=useState<any>({registrada:false}),[error,setError]=useState("");
 const load=async()=>{setRows(await fetchCollaboration("firma"));setProfile(await fetchMySignature())};useEffect(()=>{load()},[]);const toData=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)});
 const saveProfile=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError("");try{const file=new FormData(event.currentTarget).get("firma") as File;if(!file||!file.type.startsWith("image/")||file.size>1_000_000)throw new Error("Selecciona una imagen PNG o JPG menor a 1 MB");setProfile(await saveMySignature(await toData(file)));setProfileOpen(false)}catch(value){setError(value instanceof Error?value.message:"No se pudo guardar la firma")}};
 const upload=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError("");try{const form=new FormData(event.currentTarget),file=form.get("archivo") as File,ids=form.getAll("firmantes").map(String);if(!file||file.type!=="application/pdf"||file.size>3_000_000)throw new Error("Selecciona un PDF menor a 3 MB");if(!ids.length)throw new Error("Selecciona al menos una persona firmante");await createCollaboration("firma",{titulo:String(form.get("titulo")),archivoNombre:file.name,archivoData:await toData(file),firmantesIds:ids,...(form.get("fechaLimite")?{fechaLimite:new Date(String(form.get("fechaLimite"))).toISOString()}:{})});setUploadOpen(false);await load()}catch(value){setError(value instanceof Error?value.message:"No se pudo publicar el documento")}};
 const confirmSign=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!signing)return;setError("");try{await signDocument(signing.id,String(new FormData(event.currentTarget).get("password")));setSigning(null);await load()}catch(value){setError(value instanceof Error?value.message:"No se pudo firmar")}};
 const confirmReject=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!rejecting)return;setError("");try{const form=new FormData(event.currentTarget);await rejectDocument(rejecting.id,String(form.get("password")),String(form.get("motivo")));setRejecting(null);await load()}catch(value){setError(value instanceof Error?value.message:"No se pudo rechazar")}};
 const mine=(row:Row)=>row.datos.firmantes?.find((item:any)=>item.usuarioId===user.id),pending=(row:Row)=>mine(row)?.estado==="Pendiente"&&!["Rechazado","Anulado"].includes(row.datos.estado);
 return <div className="secure-signature"><section className="signature-secure-hero"><div><span><ShieldCheck/></span><div><small>DOCUMENTOS PROTEGIDOS</small><h2>Firma electrónica interna</h2><p>Asignación exclusiva, verificación de identidad e integridad SHA-256.</p></div></div><div><button onClick={()=>{setError("");setProfileOpen(true)}}><Fingerprint/>{profile.registrada?"Actualizar mi firma":"Registrar mi firma"}</button><button className="primary" onClick={()=>{setError("");setUploadOpen(true)}}><Plus/>Nuevo documento</button></div></section><div className="signature-security-strip"><span><UserCheck/>Solo firman las personas asignadas</span><span><ShieldCheck/>Contraseña requerida</span><span><FileCheck2/>PDF sellado y verificable</span></div>
 <div className="signature-secure-grid">{rows.map(row=>{const my=mine(row),signed=row.datos.estado==="Firmado";return <article key={row.id}><header><span className={signed?"signed":""}>{signed?<FileCheck2/>:<FileText/>}</span><div><h3>{row.datos.titulo}</h3><p>{row.datos.archivoNombre}</p></div><em className="signature-status">{row.datos.estado}</em></header><div className="signature-meta"><span>Creado por <b>{row.creador.nombres} {row.creador.apellidos}</b></span><span>Hash <b>{row.datos.hashOriginal?.slice(0,16)??"Documento anterior"}</b></span>{row.datos.fechaLimite&&<span>Vence <b>{new Date(row.datos.fechaLimite).toLocaleDateString("es-PE")}</b></span>}</div><div className="signature-signers">{(row.datos.firmantes??[]).map((person:any)=><span key={person.usuarioId} className={person.estado.toLowerCase()}><i>{person.nombre.split(" ").map((part:string)=>part[0]).slice(0,2).join("")}</i><b>{person.nombre}</b><small>{person.estado}</small></span>)}{!row.datos.firmantes&&<span><b>Documento de versión anterior</b></span>}</div><footer><button onClick={()=>setPreview(row)}><FileText/>Previsualizar</button>{row.datos.archivoFirmadoData&&<a href={row.datos.archivoFirmadoData} download={`firmado-${row.datos.archivoNombre}`}><Download/>Descargar firmado</a>}{pending(row)&&<><button className="sign-action" onClick={()=>{setError("");if(profile.registrada)setSigning(row);else setProfileOpen(true)}}><FileSignature/>Firmar</button><button className="reject-action" onClick={()=>{setError("");setRejecting(row)}}><XCircle/>Rechazar</button></>}{my&&my.estado!=="Pendiente"&&<span className="my-signature-state">Tu respuesta: {my.estado}</span>}</footer></article>})}{!rows.length&&<div className="signature-empty"><FileSignature/><b>No tienes documentos asignados</b><span>Los documentos que crees o debas firmar aparecerán aquí.</span></div>}</div>
 {preview&&<div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setPreview(null)}}><section className="pdf-signature-preview secure-preview"><button className="close" onClick={()=>setPreview(null)}><X/></button><header><FileText/><div><h2>{preview.datos.titulo}</h2><p>{preview.datos.archivoNombre}</p></div><span>{preview.datos.estado}</span></header><iframe src={preview.datos.archivoFirmadoData||preview.datos.archivoData}/><div className="signature-evidence"><b><ShieldCheck/>Evidencias registradas</b>{(preview.datos.evidencias??[]).map((evidence:any)=><span key={evidence.fecha}>{evidence.nombre} · {new Date(evidence.fecha).toLocaleString("es-PE")} · SHA {evidence.hashDocumentoFirmado.slice(0,16)}</span>)}{!preview.datos.evidencias?.length&&<span>Aún no se registraron firmas.</span>}</div></section></div>}
 {profileOpen&&<div className="overlay"><form className="collab-modal signature-profile-modal" onSubmit={saveProfile}><button type="button" className="close" onClick={()=>setProfileOpen(false)}><X/></button><Fingerprint/><h2>Mi firma personal</h2><p>Sube una imagen PNG o JPG. Solo se utilizará cuando confirmes una firma con tu contraseña.</p>{profile.registrada&&<img src={profile.firmaData} alt="Firma personal registrada"/>}<label>Imagen de firma<input name="firma" type="file" accept="image/png,image/jpeg" required/></label>{error&&<div className="signature-error">{error}</div>}<button className="primary"><Upload/>Guardar firma</button></form></div>}
 {uploadOpen&&<div className="overlay"><form className="collab-modal signature-upload-modal" onSubmit={upload}><button type="button" className="close" onClick={()=>setUploadOpen(false)}><X/></button><FileSignature/><h2>Nuevo documento para firma</h2><p>Será visible exclusivamente para ti y las personas seleccionadas.</p><label>Título<input name="titulo" required minLength={3}/></label><label>Documento PDF<input name="archivo" type="file" accept="application/pdf" required/></label><label>Fecha límite opcional<input name="fechaLimite" type="datetime-local"/></label><fieldset><legend>¿Quiénes deben firmar?</legend><div className="signature-people-picker">{team.map(member=><label key={member.id}><input type="checkbox" name="firmantes" value={member.id}/>{member.fotoPerfil?<img src={member.fotoPerfil}/>:<i>{member.nombres[0]}{member.apellidos[0]}</i>}<span><b>{member.nombres} {member.apellidos}</b><small>{member.area.nombre} · {member.cargo}</small></span></label>)}</div></fieldset>{error&&<div className="signature-error">{error}</div>}<button className="primary">Enviar para firma</button></form></div>}
 {signing&&<div className="overlay"><form className="collab-modal" onSubmit={confirmSign}><button type="button" className="close" onClick={()=>setSigning(null)}><X/></button><ShieldCheck/><h2>Confirmar firma</h2><p>Se estampará tu firma en el PDF y se generará una evidencia verificable.</p><div className="document-preview"><FileText/><b>{signing.datos.archivoNombre}</b></div><label>Contraseña actual<input name="password" type="password" required autoComplete="current-password"/></label><label className="signature-consent"><input type="checkbox" required/>He revisado el documento y manifiesto mi conformidad.</label>{error&&<div className="signature-error">{error}</div>}<button className="primary">Firmar documento</button><small className="legal-note">Constancia electrónica interna; no sustituye un certificado digital acreditado.</small></form></div>}
 {rejecting&&<div className="overlay"><form className="collab-modal" onSubmit={confirmReject}><button type="button" className="close" onClick={()=>setRejecting(null)}><X/></button><AlertTriangle/><h2>Rechazar documento</h2><label>Motivo<textarea name="motivo" required minLength={3}/></label><label>Contraseña actual<input name="password" type="password" required/></label>{error&&<div className="signature-error">{error}</div>}<button className="reject-confirm">Confirmar rechazo</button></form></div>}</div>;
}
