import "dotenv/config";
import jwt from "jsonwebtoken";
import { PrismaClient } from "@prisma/client";
const prisma=new PrismaClient(),base="http://localhost:4000/api",created={requests:[],rules:[],entities:[],user:null};
const token=id=>jwt.sign({sub:id},process.env.JWT_SECRET||"dev-only-secret");
async function call(path,user,options={}){const response=await fetch(base+path,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token(user.id)}`,...options.headers},body:options.body?JSON.stringify(options.body):undefined});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(`${path}: ${response.status} ${data.message||""}`);return data}
async function approve(id,admin){await call(`/aprobaciones/${id}/resolver`,admin,{method:"POST",body:{approved:true,comentario:"Etapa validada por prueba automática."}});await call(`/aprobaciones/${id}/resolver`,admin,{method:"POST",body:{approved:true,comentario:"Aprobación final validada."}})}
try{
 const admin=await prisma.usuario.findFirst({where:{isSuperAdmin:true}});if(!admin)throw new Error("Se requiere un superadministrador para la prueba");const area=await prisma.area.findFirstOrThrow();const stamp=Date.now().toString().slice(-7);
 const user=await prisma.usuario.create({data:{nombres:"Prueba",apellidos:"Aprobaciones",email:`approval-smoke-${stamp}@local.test`,passwordHash:"test-only",areaId:area.id,cargo:"Asistente",rol:"Usuario"}});created.user=user.id;
 const initiative=await prisma.iniciativa.create({data:{codigo:`QA${stamp}`,titulo:"Proyecto QA",descripcion:"Prueba controlada",areaId:area.id,impacto:5,esfuerzo:"Medio",score:5}}),objective=await prisma.objetivoNegocio.create({data:{nombre:"Objetivo QA",descripcion:"Prueba controlada"}}),requirement=await prisma.requerimiento.create({data:{titulo:"Requerimiento QA",descripcion:"Prueba",cantidad:1,prioridad:"Normal",estado:"Pendiente",areaId:area.id,usuarioId:user.id}}),document=await prisma.flujoArea.create({data:{titulo:"Documento QA",descripcion:"Prueba",archivoNombre:"qa.pdf",archivoData:"data:application/pdf;base64,JVBERi0=",areaId:area.id,usuarioId:user.id}});created.entities=[initiative.id,objective.id,requirement.id,document.id];
 for(const entidad of ["Proyectos","Objetivos","Requerimientos","Documentos"]){const rule=await prisma.registroPortal.create({data:{tipo:"regla_aprobacion",creadorId:admin.id,datos:{nombre:`QA ${entidad} ${stamp}`,entidad,area:area.nombre,etapas:["Gerente","Administración"],activa:true}}});created.rules.push(rule.id)}
 const cases=[{tipoEntidad:"Iniciativa",entidadId:initiative.id,accion:"Editar",payload:{titulo:"Proyecto QA aprobado"}},{tipoEntidad:"Objetivo",entidadId:objective.id,accion:"Eliminar"},{tipoEntidad:"Requerimiento",entidadId:requirement.id,accion:"Editar",payload:{cantidad:7}},{tipoEntidad:"Documento",entidadId:document.id,accion:"Eliminar"}];
 for(const item of cases){const request=await call("/aprobaciones",user,{method:"POST",body:{...item,motivo:"Validación integral automática"}});created.requests.push(request.id);await approve(request.id,admin)}
 const [i,o,r,d,history]=await Promise.all([prisma.iniciativa.findUnique({where:{id:initiative.id}}),prisma.objetivoNegocio.findUnique({where:{id:objective.id}}),prisma.requerimiento.findUnique({where:{id:requirement.id}}),prisma.flujoArea.findUnique({where:{id:document.id}}),call("/aprobaciones?scope=history",admin)]);
 if(i?.titulo!=="Proyecto QA aprobado"||!o?.deletedAt||r?.cantidad!==7||!d?.deletedAt||!created.requests.every(id=>history.some(row=>row.id===id&&row.estado==="Aprobada"&&row.decisiones.length===2)))throw new Error("La verificación final no coincide con los cambios aprobados");
 console.log("APPROVAL_SMOKE_OK: 4 entidades, 2 etapas, historial y papelera verificados");
}finally{
 if(created.requests.length)await prisma.solicitudCambio.deleteMany({where:{id:{in:created.requests}}});if(created.rules.length)await prisma.registroPortal.deleteMany({where:{id:{in:created.rules}}});if(created.entities.length){await prisma.iniciativa.deleteMany({where:{id:created.entities[0]}});await prisma.objetivoNegocio.deleteMany({where:{id:created.entities[1]}});await prisma.requerimiento.deleteMany({where:{id:created.entities[2]}});await prisma.flujoArea.deleteMany({where:{id:created.entities[3]}})}if(created.user)await prisma.usuario.delete({where:{id:created.user}});await prisma.$disconnect();
}
