CREATE TYPE "EstadoTicket" AS ENUM ('PENDIENTE','EN_CURSO','FINALIZADO');
CREATE TYPE "PrioridadTicket" AS ENUM ('BAJA','NORMAL','ALTA','URGENTE');
CREATE TYPE "CanalTicket" AS ENUM ('TELEFONO','CORREO','CHAT','VIDEOLLAMADA','OTRO');
CREATE TABLE "clientes" ("id" UUID NOT NULL,"ruc" VARCHAR(11),"razon_social" VARCHAR(180) NOT NULL,"telefono" VARCHAR(30),"contacto" VARCHAR(150),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "clientes_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "clientes_ruc_key" ON "clientes"("ruc");
CREATE UNIQUE INDEX "clientes_razon_social_key" ON "clientes"("razon_social");
INSERT INTO "clientes" ("id","razon_social") SELECT gen_random_uuid(),trim("cliente") FROM "iniciativas" WHERE "cliente" IS NOT NULL AND trim("cliente")<>'' GROUP BY trim("cliente") ON CONFLICT DO NOTHING;
CREATE TABLE "tickets" ("id" UUID NOT NULL,"correlativo" SERIAL NOT NULL,"cliente_id" UUID NOT NULL,"ruc" VARCHAR(11) NOT NULL,"razon_social" VARCHAR(180) NOT NULL,"modulo" VARCHAR(100) NOT NULL,"telefono" VARCHAR(30),"contacto" VARCHAR(150) NOT NULL,"consulta" VARCHAR(3000) NOT NULL,"prioridad" "PrioridadTicket" NOT NULL DEFAULT 'NORMAL',"canal" "CanalTicket" NOT NULL DEFAULT 'TELEFONO',"estado" "EstadoTicket" NOT NULL DEFAULT 'PENDIENTE',"creado_por_id" UUID NOT NULL,"registrado_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"asignado_a_id" UUID,"asignado_at" TIMESTAMP(3),"contactado_at" TIMESTAMP(3),"observaciones" VARCHAR(3000),"solucion" VARCHAR(3000),"finalizado_at" TIMESTAMP(3),"finalizado_por_id" UUID,"sla_vence_at" TIMESTAMP(3),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "tickets_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ticket_historial" ("id" UUID NOT NULL,"ticket_id" UUID NOT NULL,"accion" VARCHAR(80) NOT NULL,"estado_anterior" "EstadoTicket","estado_nuevo" "EstadoTicket","usuario_id" UUID NOT NULL,"comentario" VARCHAR(2000),"created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ticket_historial_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "tickets_correlativo_key" ON "tickets"("correlativo");
CREATE INDEX "tickets_estado_registrado_at_idx" ON "tickets"("estado","registrado_at");
CREATE INDEX "tickets_asignado_a_id_estado_idx" ON "tickets"("asignado_a_id","estado");
CREATE INDEX "tickets_cliente_id_registrado_at_idx" ON "tickets"("cliente_id","registrado_at");
CREATE INDEX "ticket_historial_ticket_id_created_at_idx" ON "ticket_historial"("ticket_id","created_at");
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_cliente_id_fkey" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_creado_por_id_fkey" FOREIGN KEY ("creado_por_id") REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_asignado_a_id_fkey" FOREIGN KEY ("asignado_a_id") REFERENCES "usuarios"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_finalizado_por_id_fkey" FOREIGN KEY ("finalizado_por_id") REFERENCES "usuarios"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ticket_historial" ADD CONSTRAINT "ticket_historial_ticket_id_fkey" FOREIGN KEY ("ticket_id") REFERENCES "tickets"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ticket_historial" ADD CONSTRAINT "ticket_historial_usuario_id_fkey" FOREIGN KEY ("usuario_id") REFERENCES "usuarios"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
