import bcrypt from "bcryptjs";import jwt from "jsonwebtoken";import crypto from "node:crypto";import {Cargo,Rol}from"@prisma/client";import{prisma}from"../config/db.js";import{sendMail}from"./mail.js";
const secret=process.env.JWT_SECRET??"dev-only-secret",hashToken=(v:string)=>crypto.createHash("sha256").update(v).digest("hex"),sessionToken=(id:string)=>jwt.sign({sub:id},secret,{expiresIn:"8h"}),publicUser=(u:any)=>({id:u.id,nombres:u.nombres,apellidos:u.apellidos,nombreCompleto:`${u.nombres} ${u.apellidos}`,email:u.email,cargo:u.cargo,rol:u.rol,portalColor:u.portalColor,darkMode:u.darkMode,fotoPerfil:u.fotoPerfil,estadoMensaje:u.estadoMensaje,isSuperAdmin:u.isSuperAdmin,permisos:u.permisos,notificationPreferences:u.notificationPreferences,onboardingCompleted:u.onboardingCompleted,emailVerified:Boolean(u.emailVerifiedAt),area:u.area});
export const authService={
async register(data:{nombres:string;apellidos:string;email:string;password:string;areaId:string;cargo:Cargo;approvalCode?:string}){if([Cargo.Jefe,Cargo.Gerente].includes(data.cargo as any) && data.approvalCode?.trim()!==(process.env.REGISTRATION_APPROVAL_CODE??"2026-2"))throw new Error("Código de aprobación incorrecto para Jefe o Gerente");const email=data.email.toLowerCase();if(await prisma.usuario.findUnique({where:{email}}))throw new Error("El correo ya está registrado");const verificationToken=crypto.randomBytes(32).toString("hex"),usuario=await prisma.usuario.create({data:{nombres:data.nombres.trim(),apellidos:data.apellidos.trim(),email,passwordHash:await bcrypt.hash(data.password,12),areaId:data.areaId,cargo:data.cargo,rol:[Cargo.Jefe,Cargo.Gerente].includes(data.cargo as any)?Rol.Comite:Rol.Usuario,verificationTokenHash:hashToken(verificationToken)},include:{area:true}}),base=process.env.FRONTEND_URL??"https://localhost:5173";await sendMail(email,"Verifica tu correo en EJB MANAGER",`Confirma tu cuenta desde ${base}/?verify=${verificationToken}`);return{token:sessionToken(usuario.id),usuario:publicUser(usuario),...(process.env.NODE_ENV!=="production"?{developmentVerificationToken:verificationToken}:{})}},
async login(email:string,password:string){const usuario=await prisma.usuario.findUnique({where:{email:email.toLowerCase()},include:{area:true}});if(usuario?.lockedUntil&&usuario.lockedUntil>new Date())throw new Error("Cuenta bloqueada temporalmente. Inténtalo nuevamente en unos minutos");if(!usuario||!await bcrypt.compare(password,usuario.passwordHash)){if(usuario){const failed=usuario.failedLoginAttempts+1;await prisma.usuario.update({where:{id:usuario.id},data:{failedLoginAttempts:failed,lockedUntil:failed>=5?new Date(Date.now()+15*60_000):null}})}throw new Error("Correo o contraseña incorrectos")}await prisma.usuario.update({where:{id:usuario.id},data:{failedLoginAttempts:0,lockedUntil:null}});return{token:sessionToken(usuario.id),usuario:publicUser(usuario)}},
async me(id:string){return publicUser(await prisma.usuario.findUniqueOrThrow({where:{id},include:{area:true}}))},
async forgot(email:string){const usuario=await prisma.usuario.findUnique({where:{email:email.toLowerCase()}});if(!usuario)return{ok:true};const raw=crypto.randomBytes(32).toString("hex");await prisma.usuario.update({where:{id:usuario.id},data:{resetTokenHash:hashToken(raw),resetExpires:new Date(Date.now()+30*60_000)}});const base=process.env.FRONTEND_URL??"https://localhost:5173";await sendMail(usuario.email,"Recupera tu acceso a EJB MANAGER",`Usa este enlace durante los próximos 30 minutos: ${base}/?reset=${raw}`);return{ok:true,...(process.env.NODE_ENV!=="production"?{developmentToken:raw}:{})}},
async reset(value:string,password:string){const usuario=await prisma.usuario.findFirst({where:{resetTokenHash:hashToken(value),resetExpires:{gt:new Date()}}});if(!usuario)throw new Error("El enlace es inválido o venció");await prisma.usuario.update({where:{id:usuario.id},data:{passwordHash:await bcrypt.hash(password,12),resetTokenHash:null,resetExpires:null,failedLoginAttempts:0,lockedUntil:null}});return{ok:true}},
async verifyEmail(value:string){const usuario=await prisma.usuario.findFirst({where:{verificationTokenHash:hashToken(value)}});if(!usuario)throw new Error("El enlace de verificación no es válido");await prisma.usuario.update({where:{id:usuario.id},data:{emailVerifiedAt:new Date(),verificationTokenHash:null}});return{ok:true}}
};
