export type Actor={id:string;areaId:string;cargo:string;rol:string;isSuperAdmin:boolean;permisos?:unknown};
export const hasPermission=(actor:Actor,key:string)=>actor.isSuperAdmin||Boolean((actor.permisos as Record<string,boolean>|null)?.[key]);
export const isTechnical=(actor:Actor)=>actor.cargo==="Tecnico";
export const hasGlobalOperationalAccess=(actor:Actor)=>actor.isSuperAdmin||isTechnical(actor);
export const isAreaLeader=(actor:Actor)=>["Jefe","Gerente"].includes(actor.cargo);
export const isAdministration=(actor:Actor)=>actor.cargo==="Administracion";
export const isManagement=(actor:Actor)=>actor.isSuperAdmin||isAreaLeader(actor);
export const canPublishAnnouncements=(actor:Actor)=>isManagement(actor)||isAdministration(actor);
export const canManageArea=(actor:Actor,areaId:string)=>hasGlobalOperationalAccess(actor)||(isAreaLeader(actor)&&actor.areaId===areaId);
export const canDeleteOwned=(actor:Actor,ownerId:string|null|undefined,areaId:string|null|undefined)=>actor.isSuperAdmin||actor.id===ownerId||(isAreaLeader(actor)&&Boolean(areaId)&&actor.areaId===areaId);
export const requiresProjectDeleteApproval=(actor:Actor)=>!actor.isSuperAdmin&&["Asistente","Trabajador"].includes(actor.cargo);
export const canApproveProjectDeletion=(actor:Actor,areaId:string)=>actor.isSuperAdmin||(actor.cargo==="Gerente"&&actor.areaId===areaId);
export const canReadInitiative=(actor:Actor,item:{areaId:string;responsableId?:string|null})=>hasGlobalOperationalAccess(actor)||isManagement(actor)||actor.areaId===item.areaId||actor.id===item.responsableId;
export const canManageInitiative=(actor:Actor,item:{areaId:string;responsableId?:string|null})=>canManageArea(actor,item.areaId)||hasPermission(actor,"editarProyectos")||actor.id===item.responsableId;
export const groupMembers=(data:any,creatorId:string):string[]=>Array.from(new Set([creatorId,...(Array.isArray(data?.miembros)?data.miembros:[])]));
export const canReadPrivateGroup=(actorId:string,data:any,creatorId:string)=>groupMembers(data,creatorId).includes(actorId);
