import { NextFunction,Request,Response } from "express";
import { z } from "zod";
import { prisma } from "../config/db.js";
import { audit } from "../services/audit.js";
import { canManageInitiative } from "../services/permissions.js";
import { automaticProjectStatus, progressFromTasks, type ProjectStatus } from "../services/project-status.js";
const dateField=z.string().optional().transform(value=>value?new Date(value):undefined);
const taskExtras={prioridad:z.enum(["Baja","Normal","Alta","Urgente"]).optional(),responsableId:z.string().uuid().nullable().optional(),recordatorioAt:z.string().nullable().optional().transform(value=>value?new Date(value):value),adjuntos:z.array(z.object({nombre:z.string().max(180),mime:z.string().max(100),data:z.string().max(4_200_000)})).max(5).optional()};
const createSchema=z.object({titulo:z.string().trim().min(2).max(220),estado:z.enum(["Pendiente","Iniciado","En_progreso"]).default("Pendiente"),comentario:z.string().trim().max(600).optional(),fechaInicio:dateField,fechaFin:dateField,...taskExtras}).refine(value=>!value.fechaInicio||!value.fechaFin||value.fechaFin>=value.fechaInicio,{message:"La fecha fin debe ser posterior al inicio"});
const updateSchema=z.object({titulo:z.string().trim().min(2).max(220).optional(),estado:z.enum(["Pendiente","Iniciado","En_progreso","Completada"]),comentario:z.string().trim().max(600).optional(),fechaInicio:dateField,fechaFin:dateField,...taskExtras}).refine(value=>!value.fechaInicio||!value.fechaFin||value.fechaFin>=value.fechaInicio,{message:"La fecha fin debe ser posterior al inicio"});
async function refreshProgress(tx:any,iniciativaId:string){
  const [total,completed,active,initiative]=await Promise.all([
    tx.tareaIniciativa.count({where:{iniciativaId,deletedAt:null}}),
    tx.tareaIniciativa.count({where:{iniciativaId,completada:true,deletedAt:null}}),
    tx.tareaIniciativa.count({where:{iniciativaId,deletedAt:null,estado:{in:["Iniciado","En_progreso"]}}}),
    tx.iniciativa.findUniqueOrThrow({where:{id:iniciativaId},select:{estado:true}}),
  ]);
  const porcentajeAvance=progressFromTasks(total,completed,0),estado=automaticProjectStatus(porcentajeAvance,initiative.estado as ProjectStatus,active>0);
  return tx.iniciativa.update({where:{id:iniciativaId},data:{porcentajeAvance,estado},select:{porcentajeAvance:true,estado:true}});
}
export async function addTask(req:Request,res:Response,next:NextFunction){try{const iniciativaId=String(req.params.id),data=createSchema.parse(req.body),actor=await prisma.usuario.findUniqueOrThrow({where:{id:req.userId!}}),initiative=await prisma.iniciativa.findUniqueOrThrow({where:{id:iniciativaId}});if(!canManageInitiative(actor,initiative))throw new Error("No tienes permisos para agregar tareas");const result=await prisma.$transaction(async tx=>{const {comentario,...taskData}=data,tarea=await tx.tareaIniciativa.create({data:{iniciativaId,...taskData,comentario:comentario||undefined,comentarios:comentario?{create:{contenido:comentario,usuarioId:req.userId!}}:undefined},include:{responsable:{select:{id:true,nombres:true,apellidos:true,fotoPerfil:true}},comentarios:{include:{usuario:{select:{id:true,nombres:true,apellidos:true,fotoPerfil:true}}},orderBy:{createdAt:'desc'}}}}),project=await refreshProgress(tx,iniciativaId);return{...tarea,porcentajeAvance:project.porcentajeAvance,estadoProyecto:project.estado}});await audit(actor.id,"Crear","Tarea",result.id,{iniciativaId,titulo:result.titulo});res.status(201).json(result)}catch(e){next(e)}}
export async function updateTask(req:Request,res:Response,next:NextFunction){try{const data=updateSchema.parse(req.body),completada=data.estado==="Completada",current=await prisma.tareaIniciativa.findUniqueOrThrow({where:{id:String(req.params.taskId)},include:{iniciativa:true}}),actor=await prisma.usuario.findUniqueOrThrow({where:{id:req.userId!}});if(!canManageInitiative(actor,current.iniciativa))throw new Error("No tienes permisos para modificar esta tarea");const result=await prisma.$transaction(async tx=>{const {comentario,...taskData}=data,tarea=await tx.tareaIniciativa.update({where:{id:current.id},data:{...taskData,comentario:comentario||current.comentario,completada,completadaAt:completada?new Date():null,comentarios:comentario?{create:{contenido:comentario,usuarioId:req.userId!}}:undefined},include:{responsable:{select:{id:true,nombres:true,apellidos:true,fotoPerfil:true}},comentarios:{include:{usuario:{select:{id:true,nombres:true,apellidos:true,fotoPerfil:true}}},orderBy:{createdAt:'desc'}}}}),project=await refreshProgress(tx,current.iniciativaId);return{...tarea,porcentajeAvance:project.porcentajeAvance,estadoProyecto:project.estado}});await audit(actor.id,completada?"Completar":"Actualizar","Tarea",result.id,{estado:data.estado,iniciativaId:current.iniciativaId});res.json(result)}catch(e){next(e)}}
