import { uiPrompt, uiAlert } from "../utils/dialog";
import { FormEvent, useEffect, useState } from "react";
import { BarChart3, CheckCircle2, FileSignature, FileText, Hash, MessageCircle, Plus, Send, UserPlus, Users, Vote, X } from "lucide-react";
import { createCollaboration, fetchCollaboration, fetchGroupInvitations, respondGroupInvitation, updateCollaboration } from "../api/iniciativas";

export type RecordRow={canDelete?:boolean;canEdit?:boolean;id:string;datos:any;creador:any;createdAt:string};
export function MessageSpaceList({onSelect,activeId}:{onSelect:(row:RecordRow)=>void;activeId?:string}){
  const [rows,setRows]=useState<RecordRow[]>([]),[invitations,setInvitations]=useState<any[]>([]);
  useEffect(()=>{let mounted=true;const load=async()=>{const [groups,channels,pending]=await Promise.all([fetchCollaboration("grupo"),fetchCollaboration("canal"),fetchGroupInvitations()]);if(mounted){setRows([...groups,...channels]);setInvitations(pending)}};load();window.addEventListener("ejb-spaces-changed",load);const timer=window.setInterval(load,3000);return()=>{mounted=false;window.clearInterval(timer);window.removeEventListener("ejb-spaces-changed",load)}},[]);
  const groups=rows.filter(row=>!row.datos.esCanal&&row.datos.tipo!=="canal"),channels=rows.filter(row=>row.datos.esCanal||row.datos.tipo==="canal");
  const option=(row:RecordRow,type:"grupo"|"canal")=><button className={activeId===row.id?"active":""} key={row.id} onClick={()=>onSelect({...row,datos:{...row.datos,tipo:type,esCanal:type==="canal"}})}>{row.datos.foto?<img className="space-avatar" src={row.datos.foto} alt=""/>:<span className="space-avatar fallback">{type==="canal"?<Hash/>:<Users/>}</span>}<span><b>{row.datos.nombre}</b><small>{row.datos.mensajes?.length??0} mensajes</small></span></button>;
  const respond=async(invitation:any,respuesta:"Aceptar"|"Rechazar")=>{const result=await respondGroupInvitation(invitation.grupoId,invitation.id,respuesta);setInvitations(current=>current.filter(item=>item.id!==invitation.id));if(result.grupo)setRows(current=>[result.grupo,...current])};
  return <div className="space-categories spaces-under-contacts">{invitations.length>0&&<section className="group-invitations"><h4><UserPlus/>Invitaciones <em>{invitations.length}</em></h4>{invitations.map(invitation=><article key={invitation.id}><span className="space-avatar fallback"><Users/></span><div><b>{invitation.grupoNombre}</b><small>Te invitó {invitation.creador.nombres} {invitation.creador.apellidos}</small></div><button onClick={()=>respond(invitation,"Aceptar")}><CheckCircle2/>Aceptar</button><button onClick={()=>respond(invitation,"Rechazar")}><X/>Rechazar</button></article>)}</section>}<section><h4><Users/>Grupos</h4>{groups.map(row=>option(row,"grupo"))}{!groups.length&&<p>Sin grupos</p>}</section><section><h4><Hash/>Canales</h4>{channels.map(row=>option(row,"canal"))}{!channels.length&&<p>Sin canales</p>}</section></div>;
}
export function MessageSpaces({currentUserId,onSelect,activeId}:{currentUserId:string;onSelect:(row:RecordRow)=>void;activeId?:string}){
  const [rows,setRows]=useState<RecordRow[]>([]),[type,setType]=useState<"grupo"|"canal"|null>(null);
  const load=async()=>setRows([...(await fetchCollaboration("grupo")),...(await fetchCollaboration("canal"))]);useEffect(()=>{load();window.addEventListener("ejb-spaces-changed",load);return()=>window.removeEventListener("ejb-spaces-changed",load)},[]);
  const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!type)return;const f=new FormData(e.currentTarget),file=f.get("foto") as File;let foto="";if(file?.size){if(!file.type.startsWith("image/")||file.size>2000000)return alert("La foto debe ser una imagen menor a 2 MB");foto=await new Promise<string>(ok=>{const reader=new FileReader();reader.onload=()=>ok(String(reader.result));reader.readAsDataURL(file)})}await createCollaboration(type,{tipo:type,esCanal:type==="canal",nombre:String(f.get("nombre")),descripcion:String(f.get("descripcion")),foto,mensajes:[],miembros:[currentUserId]});setType(null);load();window.dispatchEvent(new Event("ejb-spaces-changed"))};
  return <><div className="space-toolbar"><div><b>Conversaciones de equipo</b><span>Grupos privados y canales para las áreas</span></div><button onClick={()=>setType("grupo")}><Users/>Crear grupo</button><button onClick={()=>setType("canal")}><Hash/>Crear canal</button></div><div className="space-chips">{rows.map(row=><button key={row.id} onClick={()=>onSelect({...row,datos:{...row.datos,tipo:row.datos.esCanal?"canal":row.datos.tipo??"grupo"}})}><span>{row.datos.esCanal||row.datos.tipo==="canal"?<Hash/>:<Users/>}</span><b>{row.datos.nombre}</b><small>{row.datos.mensajes?.length??0}</small></button>)}</div>
  <div className="space-categories"><section><h4><Users/>Grupos</h4>{rows.filter(row=>!row.datos.esCanal&&row.datos.tipo!=="canal").map(row=><button className={activeId===row.id?"active":""} key={row.id} onClick={()=>onSelect({...row,datos:{...row.datos,tipo:"grupo"}})}>{row.datos.foto?<img className="space-avatar" src={row.datos.foto}/>:<span className="space-avatar fallback"><Users/></span>}<span><b>{row.datos.nombre}</b><small>{row.datos.mensajes?.length??0} mensajes</small></span></button>)}{!rows.some(row=>!row.datos.esCanal&&row.datos.tipo!=="canal")&&<p>Sin grupos</p>}</section><section><h4><Hash/>Canales</h4>{rows.filter(row=>row.datos.esCanal||row.datos.tipo==="canal").map(row=><button className={activeId===row.id?"active":""} key={row.id} onClick={()=>onSelect({...row,datos:{...row.datos,tipo:"canal",esCanal:true}})}>{row.datos.foto?<img className="space-avatar" src={row.datos.foto}/>:<span className="space-avatar fallback"><Hash/></span>}<span><b>{row.datos.nombre}</b><small>{row.datos.mensajes?.length??0} mensajes</small></span></button>)}{!rows.some(row=>row.datos.esCanal||row.datos.tipo==="canal")&&<p>Sin canales</p>}</section></div>
  {type&&<div className="overlay"><form className="collab-modal" onSubmit={create}><button type="button" className="close" onClick={()=>setType(null)}><X/></button>{type==="grupo"?<Users/>:<Hash/>}<h2>Crear {type}</h2><p>{type==="canal"?"Espacio abierto para coordinar un área.":"Conversación para un equipo específico."}</p><label>Nombre<input name="nombre" required maxLength={80}/></label><label>Descripción<textarea name="descripcion" maxLength={300}/></label><label>Foto del {type}<input name="foto" type="file" accept="image/*"/></label><input type="hidden" name="esCanal" value={String(type==="canal")}/><button className="primary">Crear espacio</button></form></div>}
  </>;
}

export function ElectronicSignature({user}:{user:any}){
 const [rows,setRows]=useState<RecordRow[]>([]),[modal,setModal]=useState(false),[signing,setSigning]=useState<RecordRow|null>(null),[preview,setPreview]=useState<RecordRow|null>(null);const load=()=>fetchCollaboration("firma").then(setRows);useEffect(()=>{load()},[]);
 const upload=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),file=f.get("archivo") as File;if(!file||file.type!=="application/pdf"||file.size>3000000)return;const data=await new Promise<string>(ok=>{const r=new FileReader();r.onload=()=>ok(String(r.result));r.readAsDataURL(file)});await createCollaboration("firma",{titulo:String(f.get("titulo")),archivoNombre:file.name,archivoData:data,estado:"Pendiente",firmas:[]});setModal(false);load()};
 const sign=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!signing)return;const f=new FormData(e.currentTarget),firma=String(f.get("firma"));await updateCollaboration("firma",signing.id,{...signing.datos,estado:"Firmado",firmas:[...(signing.datos.firmas??[]),{usuarioId:user.id,nombre:firma,fecha:new Date().toISOString()}]});setSigning(null);load()};
 return <div className="signature-module"><div className="module-hero"><div><FileSignature/><span><b>Firma Electrónica</b><small>Documentos internos, trazabilidad y constancia de firma</small></span></div><button className="primary" onClick={()=>setModal(true)}><Plus/>Subir documento</button></div><div className="signature-grid">{rows.map(row=><article key={row.id}><span className={row.datos.estado==="Firmado"?"signed":""}><FileText/></span><div><h3>{row.datos.titulo}</h3><p>{row.datos.archivoNombre}</p><small>Subido por {row.creador.nombres} {row.creador.apellidos}</small></div><em>{row.datos.estado}</em><button onClick={()=>setPreview(row)}>Previsualizar</button>{row.datos.estado!=="Firmado"&&row.creador.id===user.id&&<button onClick={()=>setSigning(row)}>Firmar</button>}</article>)}</div>
 {preview&&<div className="overlay" onMouseDown={event=>{if(event.target===event.currentTarget)setPreview(null)}}><section className="pdf-signature-preview"><button className="close" onClick={()=>setPreview(null)}><X/></button><header><FileText/><div><h2>{preview.datos.titulo}</h2><p>{preview.datos.archivoNombre}</p></div><span>{preview.datos.estado}</span></header><iframe src={preview.datos.archivoData} title={`Vista previa de ${preview.datos.titulo}`}/></section></div>}
 {modal&&<div className="overlay"><form className="collab-modal" onSubmit={upload}><button type="button" className="close" onClick={()=>setModal(false)}><X/></button><FileSignature/><h2>Nuevo documento</h2><p>Sube un PDF de hasta 3 MB para iniciar el proceso interno.</p><label>Título<input name="titulo" required/></label><label>Documento PDF<input name="archivo" type="file" accept="application/pdf" required/></label><button className="primary">Publicar para firma</button></form></div>}{signing&&<div className="overlay"><form className="collab-modal" onSubmit={sign}><button type="button" className="close" onClick={()=>setSigning(null)}><X/></button><CheckCircle2/><h2>Confirmar firma</h2><p>Escribe tu nombre completo. Se registrará junto con la fecha y tu usuario.</p><div className="document-preview"><FileText/><b>{signing.datos.archivoNombre}</b></div><label>Firma electrónica<input className="signature-input" name="firma" defaultValue={user.nombreCompleto} required/></label><button className="primary">Firmar documento</button><small className="legal-note">Constancia electrónica interna; no sustituye un certificado digital acreditado.</small></form></div>}</div>;
}

export function Surveys({user}:{user:any}){
 const [rows,setRows]=useState<RecordRow[]>([]),[modal,setModal]=useState(false);const load=()=>fetchCollaboration("encuesta").then(setRows);useEffect(()=>{load()},[]);
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget),options=String(f.get("opciones")).split("\n").map(x=>x.trim()).filter(Boolean);if(options.length<2)return;await createCollaboration("encuesta",{pregunta:String(f.get("pregunta")),descripcion:String(f.get("descripcion")),opciones:options,votos:{},activa:true});setModal(false);load()};
 const vote=async(row:RecordRow,index:number)=>{await updateCollaboration("encuesta",row.id,{action:"vote",opcion:index});load()};
 const editSurvey=async(row:RecordRow)=>{
  const pregunta=await uiPrompt("Editar encuesta",row.datos.pregunta);if(!pregunta)return;
  const descripcion=await uiPrompt("Descripción",row.datos.descripcion||"",{multiline:true});if(descripcion===null)return;
  let opciones=row.datos.opciones;
  if(!Object.keys(row.datos.votos??{}).length){const text=await uiPrompt("Opciones, una por línea",opciones.join("\n"),{multiline:true});if(text===null)return;opciones=text.split("\n").map(value=>value.trim()).filter(Boolean);}
  try{await updateCollaboration("encuesta",row.id,{pregunta,descripcion,opciones});load();}catch(error){await uiAlert("No se pudo editar",String(error));}
 };
 return <div className="survey-module"><section className="flow-hero survey-ejb-hero"><div className="flow-hero-icon"><Vote/></div><div><span>PARTICIPACIÓN INTERNA</span><h2>Encuestas EJB</h2><p>Escucha al equipo y decide con información compartida.</p></div><button className="survey-hero-action" onClick={()=>setModal(true)}><Plus/><b>Nueva encuesta</b></button></section><div className="survey-grid">{rows.map(row=>{const entries=Object.entries(row.datos.votos??{}) as [string,any][],total=entries.length,myVote=row.datos.votos?.[user.id],myIndex=typeof myVote==="number"?myVote:myVote?.opcion;return <article key={row.id}><header><span><BarChart3/></span><div><h3>{row.datos.pregunta}</h3><p>{row.datos.descripcion}</p></div><em>{total} votos</em></header>{row.canEdit&&<div className="survey-actions"><button onClick={()=>void editSurvey(row)}>Editar encuesta</button><button onClick={async()=>{await updateCollaboration("encuesta",row.id,{activa:row.datos.activa===false});load()}}>{row.datos.activa===false?"Reabrir":"Cerrar encuesta"}</button></div>}<div className="poll-options">{row.datos.opciones.map((option:string,index:number)=>{const voters=entries.filter(([,value])=>(typeof value==="number"?value:value?.opcion)===index),percent=total?Math.round(voters.length/total*100):0;return <button disabled={row.datos.activa===false} className={myIndex===index?"selected":""} key={option} onClick={()=>vote(row,index)}><span><b>{option}</b><em>{percent}%</em></span><i><strong style={{width:`${percent}%`}}/></i><small className="poll-voters">{voters.length?voters.map(([id,value])=>typeof value==="number"?(id===user.id?user.nombreCompleto:"Voto registrado"):value.nombre).join(", "):"Aún sin votos"}</small></button>})}</div><small>Creada por {row.creador.nombres} {row.creador.apellidos} · voto único editable</small></article>})}</div>{modal&&<div className="overlay"><form className="collab-modal" onSubmit={create}><button type="button" className="close" onClick={()=>setModal(false)}><X/></button><Vote/><h2>Nueva encuesta</h2><label>Pregunta<input name="pregunta" required/></label><label>Descripción<textarea name="descripcion"/></label><label>Opciones, una por línea<textarea name="opciones" placeholder={'Opción 1\nOpción 2'} required/></label><button className="primary">Publicar para todo EJB</button></form></div>}</div>;
}
